<?php

return [
    'twig' => [
        'form_themes' => [
            'bootstrap_3_layout.html.twig',
            '@MelisPlatformFrameworkSymfony/Form/form_label_with_tooltip_template.html.twig'
        ]
    ],
    'symfony_tpl' => [
        'table' => [
            'symfony_tpl_table' => [
                'ajaxUrl' => '/melis/get-sampleEntity-data',
                'dataFunction' => '',
                'ajaxCallback' => '',
                'attributes' => [
                    'id' => 'tableSymfonyTplTool',
                    'class' => 'table table-striped table-primary dt-responsive nowrap',
                    'cellspacing' => 0,
                    'width' => '100%'
                ],
                'filters' => [
                    'left' => [
                        'show' => 'l'
                    ],
                    'center' => [
                        'search' => 'f'
                    ],
                    'right' => [
                        'refresh' => '<a class="btn btn-default melis-refreshTable" data-toggle="tab" aria-expanded="true" title="Refresh"><i class="fa fa-refresh"></i></a>'
                    ]
                ],
                'columns' => [],
                'searchables' => [],
                'actionButtons' => [
                    'edit' => '<button class="btn btn-success" id="btn-update-sampleEntity" title="Edit"><i class="fa fa-pencil"></i></button>',
                    'delete' => '<a class="btn btn-danger" id="btn-delete-sampleEntity" title="Delete"><i class="fa fa-times"> </i></a>'
                ]
            ]
        ],
        'modal' => [
            'symfony_tpl_modal' => [
                'id' => 'symfonyTplToolModal',
                'btnSubmitText' => 'Save',
                'btnSubmitId' => 'btn-save-symfonyTplTool',
                'tabs' => [
                    'tab_properties' => [
                        'title' => 'Properties',
                        'content' => 'Test content',
                        'class' => 'glyphicons plus'
                    ]
                ]
            ]
        ]
    ]
];
