#in this route, we added a prefix /melis
#because we wan't our route to access
#data in the Melis Platform Back office
#if you didn't put a /melis in your route
#then it will get the data from the front (site)

get_tool:
  path: /melis/get-SymfonyTpl-tool
  controller: App\Bundle\SymfonyTpl\Controller\SampleEntityController::getSymfonyTplTool

get_data:
  path: /melis/get-sampleEntity-data
  controller: App\Bundle\SymfonyTpl\Controller\SampleEntityController::getSampleEntityData

#Get form - if id is not null, the form will be filled with data based on given id
create_form:
  path: /melis/get-sampleEntity-form/{id}
  controller : App\Bundle\SymfonyTpl\Controller\SampleEntityController::createSampleEntityForm
  defaults:   { id: 0 }
  methods: GET|HEAD

#Save
save_album:
  path: /melis/save-sampleEntity/{id}
  controller: App\Bundle\SymfonyTpl\Controller\SampleEntityController::saveSampleEntity
  defaults:   { id: 0 }
  methods: POST

#Delete
delete_album:
  path: /melis/delete-sampleEntity
  controller: App\Bundle\SymfonyTpl\Controller\SampleEntityController::deleteSampleEntity
  methods: POST