services:
  App\Bundle\SymfonyTplBundle\Repository\SampleRepository:
    autowire: true
    tags: ['doctrine.repository_service']
  #registering a locale listener to use the melis platform language with higher priority
  App\Bundle\SymfonyTplBundle\EventListener\LocaleListener:
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }